### ISSUE TITLE
The name is the other way around

### ISSUE THREAD

**Issue by paradoja** [ayosec/qr2text#1]
`qr2text` seems to imply that the application transforms a QR into text, when it does quite the opposite.

**Comment by ayosec** [comment]
Yep, naming is hard.

I chose `qr2text` because the main difference with most QR encoders is that this tool generates the QR using Unicode block characters. so it can be considered “text” instead of an image. 

Maybe, a better name can be something like `qr-term` or so.

**Comment by paradoja** [comment]
Mhhh, now that I read your explanation the name makes sense to me xD . Maybe add that line to the Readme?

(I'd consider this issue resolved.)

**Comment by ayosec** [comment]
> Maybe add that line to the Readme?

How about this?

```diff
-A CLI program to render a QR code directly on the terminal.
+A CLI program to render a QR code as plain text, using [block symbols](https://en.wikipedia.org/wiki/Block_Elements).

```

**Comment by paradoja** [comment]
:+1:  :D
